{
 "title": "skanestas trade",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "ask_01",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  asctime AS \"time\",\r\n  ask_01 AS metric\r\nFROM trade\r\n\r\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "bid_01",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  asctime AS \"time\",\n  bid_01 AS metric\nFROM trade\n\nORDER BY 1,2\n"
    }
   ]
  },
  {
   "title": "ask_01+bid_01",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  ask_01+bid_01,asctime as time\nFROM\n trade\n"
    }
   ]
  },
  {
   "title": " ask_01+bid_01<105 ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  asctime AS \"time\",\n  ask_01+bid_01 AS metric\nFROM trade\nwhere ask_01+bid_01<105 \n"
    }
   ]
  }
 ]
}